#+latex_header: \usepackage[utf8]{inputenc}
* אײנשטײנס רעלאַטיװיטעטסטעאָריע (Einstein's Relativity Theory), Yehuda Lehman, Berlin 1921
Scanned pages of the original book found [[https://web.archive.org/web/20150817003744/http://hos.ou.edu/galleries//20thCentury/Einstein/1921/][here]]
** פֿאָרװאאאָרט
   מיטן פֿאָרליגענדען ביכעל האָב איך מיר געשטעלט די אױפֿגאַבע באַקאַנט צו
  מאַכען אַ ברײטערען עולם מיט די גרונד-יסודות פֿון אײנשטײנס
  רעלאַטיװיטעטס-טעאָריע. איך האָב געהאַט אין זינען הױפּטזעכליך אַ לעזער, װאָס
  באַזיצט אױפֿן געביט פֿון מאַטעמאַטיק און נאַטורװיסענשאַפֿט נור גאַנץ װײניג
  קענטענישען, און האָב דעריבער נישט אַרײנגעפֿירט קײן מאַטעמאַטישע פֿאָרמולן,
  װעלכע װאָלטען אַזאַ לעזער נאָר אָפּגעשראַקען. צוליב דעמזעלביגען טעם האָב איך
  יעדען װיסענשאַפֿטליכען באַגריף, װעלכען איך פֿיר אַרײן, צוערשט דעפֿינירט
  און גענױ ערקלערט, אַזױ אַז דאָס ביכעל קען מיט ערפֿאָלג אױך אַ מענש, װעלכען
  די דערמאגטע װיסענשאַפֿטען זענען לגמרי פֿרעמד.

  די באַאַרבײטונג פֿון פּראָבלעם אין דער ײדישער שפּראַך װעלכע איז נאָך, צום
  באַדױערן, אַזױ אַרעם אין װיסענשאַפֿטליכער ליטעראַטור און װעלכער עס פֿעלען
  נאָך מחמת דעם די נױטיגסטע װיסענשאַפֿטליכע אױסדרוקען, האַט געפֿאַדערט א סך
  מי. דאָס איז מיר באַדײטענד דערלײכטערט געװאַרען דורך דער הילף און
  מיטאַרבײט פֿון מײן פֿרײנד בנימין ראָזען, װעלכען איך דריק דאָ אױס דערפֿאַר א
  האַרציגען דאַנק.

  פּראָפֿ. אַלבערט אײנשטײן האַט גענומען אױף זיך די מי זיך צו באַקענען מיטן
  אינהאַלט פֿון מײן אַרבײט און דערבײ מיר צו געבען מאַנכע װערטפֿולע
  עצות. פֿאַר זײן פֿרײנדליכע אױפֿמערקזאַמקײט דריק איך אים אױך דאַ אױס מײן
  טיפֿסטען דאַנק.

  אױב דאָס ביכעל װעט מיטהעלפֿען דעם לעזער צו באַגרײפֿען די טיפֿע און שײנע
  געדאַנקען פֿון דער רעלאַטיװיטעטס-טעאָריע און דערװעקען אין אים אַ אינטערעס
  װײטער און גרינדליכער זיך צו באַשעפֿטיגען מיט די באַרירטע פּראָבלעמען, װעט
  עס האָבען דערגרײכט זײן עיקר-ציל.

  יהודה לעהמאַן

  בערלין, פֿעברואַר 1921
** I. די שװעריקײטען אין דער קלאַסישער פֿיזיק.

   --- p. 7

   די אַלגעמײנע רעלאַטיװיטעטס-טעאָריע, װעלכע איז געשאַפֿען געװאַרען דורכן
   באַרימטען יידיש-דײטשען געלערטען, פּראָפֿעסאָר אַלבערט אײנשטײן, האַט, װי
   יעדע גרױסע טעאָריע, אַ באַדײטונג נישט בלױז פֿאַר דעם צװײג פֿון דער
   װיסענשאַפֿט, צו װעלכען זי געהערט אוממיטעלבאַר: זי איז אַ פּראָדוקט און אַ
   פּועל-יוצא פֿון דער װיסענשאַפֿטליכער פֿאָרשונג און פֿילאָזאָפֿישען דענקען פֿון
   אַ גענצער עפּאָכע, און איז באַרופֿען ראַדיקאַל צו ענדערן אַלע אונזערע
   ביזאַהעריגע באַגריפֿען װעגען דער װעלט, אין װעלכער מיר לעבען.

   אין ענגערן זין געהערט די אַלגעמײנע רעלאַטיװיטעטס-טעאָריע צום געביט פֿון
   דער טעאָרעטישער פֿיזיק, װעלכע שטעלט זיך אַלס ציל אױסצופֿאָרשען דעם
   צוזאַמענהאַנג צװישען די ערשײנונגען פֿון דער אַרומיגער װעלט און צו
   געפֿינען די געזעצען, װעלכע רעגירען מיט זײ.

   באַאָבאַכטענדיג אַ װעלכע נישט איז נאַטור-ערשײנונג אָדער אַ גאַנצע גרופּע פֿון
   ערשײנונגען, זוכט דער געלערטער צו געפֿינען זײער סבה און אינערליכען
   צוזאַמענהאַנג. ער שטעלט אױף דערבײ פֿאַרשידענע השערות, פֿון װעלכע ער
   קלױבט אױס די, װעלכע איז לױט זײן מײנונג די װאַרשײנליכסטע. די השערה
   אָדער פֿאָרשטעלונג, װעלכע גיט דעם געלערטען די מעגליכקײט צו ערקלערן די
   סבה פֿון אַ נאַטור-ערשײנונג אָדער פֿון אַ גרופּע ערשײנונגען, הײסט
   היפּאָטעזע.

   --- p. 8

   אַ היפּאָטעזע װערט נור דאַמאַלס אַנערקענט פֿאַר ריכטיג, װען זי װערט
   באַשטעטיגט דורך אַלע ערשײנונגען, װעלכע מיר באַאָבאַכטען. שטױסען מיר זיך
   אַן אױף אַ ערשײנונג, װעלכע שטײט אין אַ װידערשפּרוך צו אַ אַנגענומענער
   היפּאָטעזע, מוז זי ערקלערט װערען פֿאַר פֿאַלש און במילא אָפּגעװאַרפֿען װערען.

   היפּאָטעזעס ענטשטײען און פֿאַרשװינדען מאַסענװײז אױף אַלע געביטען פֿון דער
   װיסענשאַפֿט, אַבער נור אײנצעלנע פֿון זײ װערען אין משך פֿון דער
   װײטערדינגער פֿאָרשונג באַשטעטיגט און האַבען דאָס גליק צו דינען פֿאַר אַ
   אױסגאַנגס-פּונקט פֿון אַ װיסענשאַפֿטליכער טעאָריע.

   דער געלערטער באַנוגענט זיך נישט מיט דער ערקלערונג פֿון אײן
   ערשײנונג. ער זוכט צו ערקלערן מיט זײן היפּאָטעזע און מיט דער הילף פֿון
   מאַטעמאַטישע און לאָגישע אױספֿירן אױך אַנדערע ערשײנונגען פֿון דער
   נאַטור. דער סכום פֿון אַט די אַלע אױספֿירן, װעלכע מיר מאַכען פֿון דער
   אײנמאַל אַנגענומענער היפּאָטעזע, און װעלכע גיבען די מעגליכקײט צו
   ערקלערן אַ גאַנצע רײ נאַטור-ערשײנונגען אין זײער צוזאַמענהאַנג, װערט
   אַנגערופֿען טעאָריע.

   בײ דער אױפֿשטעלונג פֿון טעאָריעס באַנוצט מען זיך אױך מיט אַזױ גערופֿענע
   פּרינציפּען. פּונקט אַזױ װי אין דער מאַטעמאַטיק זענען פֿאַרהאַן אײניגע
   כללים, די אַזױ גערופֿענע אַקסיאָמעס, אין דער ריכטיקײט פֿון װעלכע קײנער
   צװײפֿעלט נישט און װעלכע לאָזען זיך דאָך נישט באַװײזען (צום בײשפּיל דער
   כלל אין דער געאָמעטריע, אַז צװישען צװײ פּונקטען קען מען דורכפֿירען נור
   אײן גראַדע ליניע), אַזױ זענען אױך אין דער פֿיזיק פֿאַרהאַן אַלגעמײנע
   גרונד-אמת'ן, װעלכע האַבען זיך באַקומען פֿון דער ערפֿאַרונג, און װעלכע
   מען קען נישט לאָגיש באַגרינדען אָדער אַרױספֿירן פֿון אַנדערע
   געזעצען. אַזעלכע אומבאַװײזבאַרע און דאָך אַלגעמײן אַנערקענטע גרונד-אמת'ן
   װערען אַנגערופֿען אין דער פֿיזיק פּרינציפּען.

   --- p. 9
   
   דעם גרונד-יסוד פֿון דער פֿיזיק בילדען דרײ פּרינציפּען, װעלכע זענען
   באַקאַנט אונטערן נאַמען "די דרײ געזעצען פֿון ניוטאָן" . דער װיכטיגסטער
   פֿון זײ איז דער אזױ גערופֿענער פּרינציפּ פֿון אינערציע, װעלכער איז
   צוערשט אַרױסגעזאַגט געװאַרען דורך גאַלילײ (געבױרען 1564, געשטאָרבען
   1642) און גענױ פֿאָרמולירט געװאָרען דורך ניוטאָן (1643-1727), און איז
         דעריבער באַקאַנט אונטערן נאַמען: דאָס ערשטע געזעץ פֿון ניוטאָן.

   דאָס דאָזיגע געזעץ לױטעט: „יעדער קערפּער, װאָס געפֿינט זיך אין צושטאַנד
   פֿון רוּ אָדער פֿון גלײכמעסיגער גראַדליניגער באַװעגונג, פֿאַרבלײבט שטענדיג
   אין דעם צושטאַנד, ביז ער װערט נישט געצװאונגען דורך אַ אױסערליכען כּח,
   דעם דאָזיגען צושטאַנד צו ענדערן”.

   אונטער אַ גלײכמעסיגער גראַדליניגער באַװעגונג פֿאַרשטײט מען אַ באַװעגונג,
   װעלכע קומט פֿאָר אין דער ריכטונג פֿון אַ גראַדער ליניע (גראַדליניג), און
   בײ װעלכער דער קערפּער מאַכט דורך אין גלײכע צײטען גלײכע שטרעקעס, דאָס
   הײסט אַלזאָ װען דער קערפּער באַװעגט זיך שטענדיג מיט דערזעלביגער שנעלקײט
   (גלײכמעסיג).

   יעדער װײס צ.ב. פֿון דער מעגליכער ערפֿאַרונג, אַז אַ ליגענדיגען שטײן קען
   רירען פֿון אָרט נור אַ שטױס מיט דער האַנד, דער כּוח פֿון װינד אָדער אַ
   ענליכע אױסערליכע קראַפֿט. מיר זעהען אַלזאָ, אַז אַ קערפּער, װאָס געפֿינט זיך
   אין רוּ, קען נישט פֿון זיך אַלײן קומען אין באַװעגונג, אַז דערצי איז
   נױטיג אַ אױסערליכער כּוח, װעלכער זאָל אים דערצו צװינגען.

   געפֿינט זיך שױן אַבער אַ קערפּער (אין אונזער בײשפּיל דער שטײן) אין
   צושטאַנד פֿון באַװעגונג, דאַן זעהען מיר, װי ער שטעלט ביסלעכװײז און
   לאַנגזאַם אָפּ זײן באַװעגונג, ביז ער קומט ענדליך װידער אין צושטאַנד פֿון
   רוּ. די צײט, װעלכע דער קערפּער באַדאַרף, כּדי צוריקצוקומען אין צושטאַנד
   פֿון רוּ, איז נישט שטענדיג גלײך און איז אַפּהענגיג פֿון פֿאַרשידענע
   אױסערליכע

   --- p. 10

   באַדינגונגען: צ.ב. אַ קײלעכדיגער שטײן װעט זיך לענגער קאָלערן, װי אַ
   שפּיציגער, אױף זאַמד װעט ער זיך גיכער אָפּשטעלען, אײדער אױף אַ גלאַטען
   אַספֿאַלט; אַ גוט אױסגעשלײפֿטער קײלעכדיגער שטײן, געװאָרפֿען אױף אַ
   גליטשיגען אײז, װעט באַדאַרפֿען אַ גאַנץ לאַנגע צײט, כּדי זיך ענדליך
   אָפּצושטעלען.

   דאָס האַט געבראַכט גאַלילײען צום געדאַנק, אַז אײגענטליך װאָלט אַ קערפּער,
   װאָס געפֿינט זיך שױן אין צושטאַנד פֿון באַװעגונג, געמוזט תּמיד זיך װײטער
   באַװעגען מיט דערזעלביגער שנעלקײט, און אַז נור די װירקונג פֿון
   אױסערליכע כּוחות (אין אונזער בײשפּיל די רײבונג פֿון שטײן אַן די אַרומיגע
   געגענשטאַנדען, דער װידערשטאַנד פֿון דער לופֿט אַ.אַ.װ.) צװינגען דעם
   קערפּער אָפּצושטעלען זײן באַװעגונג. די ראָזיגע באַאָבאַכטונג האָט געפֿירט צו
   דער אױפֿשטעלונג פֿון אױבען פֿאָרמולירטען פּרינציפּ פֿון אינערציע, אָדער
   ערשטען ניוטאָנישען געזעץ.

   עס איז קלאַר, אַז בײ אונז אױף דער ערד זענען נישט געגעבען די
   באַדינגונגען, בײ װעלכע דאָס ערשטע ניוטאָנישע געזעץ זאָל זיך קענען
   אַרױסװײזען אין זײן רײנער געשטאַלט. כּל זמן מיר קענען נישט באַזײטיגען
   אַלע אױסערליכע כּוחות, װעלכע װירקען אױף דער ערד (די צוציהונגס-קראַפֿט
   פֿון דער ערד, די רײבונג פֿון דער לופֿט א.אַ.װ.), איז אַ באַװעגונג פֿון אַ
   קערפּער, װעלכע זאָל פֿאַרקומען תּמיד מיט דערזעלביגער שנעלקײט (אָן דער
   װירקונג פֿון אַ זײטיגען כּוח) נישט מעגליך. דאָך גילט דאָס דאָזיגע געזעץ
   אַלס אַקסיאָמע אין דער פֿיזיק.

   לאָמיר זיך אַצינד פֿאַרשטעלען אַ קערפּער אין צושטאַנד פֿון גלײכמעסיגער
   גראַדליניגער באַװעגונג. [fn::מיר נעמען אַן, אַז עס איז אונז געלונגען צו
   באַזײטיגען אַלע אױבען אױסגערעכענטע שטערונגען, און עס זענען אַלזאָ נישט
   נױטיג קײן זײטיגע כּוחות, כּדי דעם קערפּער אין דאָזיגען צושטאַנד
   אײנצוהאַלטען.] לאָמיר אים דערלאַנגען אַ שטױס אין דער פֿיכטונג פֿון זײן
   באַװעגונג. דער קערפּער װעט, אונטערן אײנפֿלוס פֿון דאָזיגען אױסערליכען
   כּוח, פֿאַרגרעסערן זײן שנעלקײט. נאָך אַ צװײטען שטױס װעט זײן שנעלקײט נאָך
   גרעסער װערען, און אױב דער אױסערליכער כּוח װעט אױף אים כּסדר װירקען,
   װעט די שנעלקײט פֿון זײן באַװעגונג כּסדר גרעסער װערען: די באַװעגונג װעט
   אױפֿהערען צו זײן אַ גלײכמעסיגע. דער אױסערליכער כּוח גיט צו דעם קערפּער
   אין יעדען שטיקעל צײט (אין יעדער סעקונדע) אַ באַשטימטען צוװאַקס פֿון
   שנעלקײט, און מיר באַקומען אַלזאָ אַ באַװעגונג מיט אַ כּסדר װאַקסענדיגער
   שנעלקײט.

   אַזאַ באַװעגונג מיט אַ כּסדר װאַקסענדיגער שנעלקײט רופֿען מיר אָן "אַ
   פֿאַרגיכערטע אבאַװעגונג" און דעם צוװאַקס פֿון שנעלקײט אין אַ באַשטימטער
   צײט-אײנהײט - "פֿאַרגיכערונג".

   װאָס גרעסער עס איז דער אױסערליכער כּוח, אַלץ מער שנעלקײט פֿון דער
   באַװעגונג פֿון קערפּער: ער קען ענדערן אױך די ריכטונג פֿון דער באַװעגונג,
   אַזױ אַז זי זאָל אױפֿהערען צו זײן גראַדליניג.

   אַרױסגײענדיג פֿון אױבען געזאַגטען, האָט ניוטאָן אױפֿגעשטעלט זײן צװײטען
   פּרינציפּ, העלכער הײסט "דאָס צװײטע ניוטאָנישע געזעץ": "װאָס גרעסער עס
   איז דער װירקענדיגער כּוח, אַלץ גרעסער איז די ענדערונג,װעלכע ער רופֿט
   אַרױס אין דער באַװעגונג. די ענדערונג קומט פֿאַר און דערזעלביגער
   ריכטונג, אין װעלכער עס װירקט דער כּוח".

   מיט אַנדערע װערטער װערט דאָס געזעץ אַזױ אױסגעדריקט: "די ענדערונג פֿון
   דער באַװעגונג פֿון אַ קערפּער איז פּראָפּאָרציאָנעל צום װירקענדיגען כּוח און
   קומט פֿאַר אין זײן ריכטונג".

   יעדער קערפּער האָט עפּעס אַזױנס, װאָס רעגולירט דאָס פֿאַרהעלטניש צװישען דעם
   װירקענדיגען כּוח און דער פֿאַרגיכערונג, װעלכע װערט דורך אים
   אַרױסגערופֿען: דאָס איז דער סכום פֿון מאַטעריע (שטאָף), װאָס איז פֿאַרהאַן
   אין קערפּער, אָדער, װי מען רופֿט עס, זײן מאַסע.

   װאָס גרעסער עס איז די מאַסע פֿון אַ קערפּער, אַלץ אַ גרעסערן כּוח דאַרף מען
   אַנװענדען, כּדי אַרױסצורופֿען אַ באַשטימטע פֿאַרגיכערונג.

   ענדליך דאָס דריטע ניוטאָנישע געזעץ לױטעט: "יעדע װירקונג רופֿט אַרױס אַ
   געגענװירקונג פֿון דערזעלביגער שטאַרקײט און אין דער פֿאַרקערטער
   ריכטונג".

   צ.ב. אַ קלאַפּ מוענדיג מיט דער האַנד אין טיש, פֿילען מיר דעם קלאַפּ, װאָס
   דער טיש גיט אונזער האַנד צוריק. ציהענדיג פֿאַר אַ שטריק, שפּירען מיר, װי
   אונזער האַנד װערט געצױגען דורך עפּעס אַ קראַפֿט אין דער פֿאַרקערטער
   ריכטונג אַ. דגל. עס איז אױך באַװיזען געװאָרען, אַז די דאָזיגע צװײ כּוחות
   זענען גלײך, אין הסכּם מיטן פֿאָרמולירטען געזעץ.
   
   די אױסגערעכענטע 3 ניוטאָנישע געזעצען בילדען די הױפּט-יסודות, אױף
   װעלכע עס איז אױפֿגעבױט די גאַנצע קלאַסישע פֿיזיק און די מעכאַניק. אַלע
   געזעצען פֿון דער פֿיזיק און מעכאַניק זענען אַ לאָגישער פּועל-יוצא פֿון די
   דאָזיגע הױפּט-געזעצען און זענען פֿון זײ אַרױסגעפֿירט.

   מיר האָבען דאַ אַפֿט זיך באַנוצט מיט די באַגריפֿען "באַװעגונג" און
   שנעלקײט". אײדער מיר גײען װײטער, מוזען מיר זײ נאָך גענױער ערקלערן".

   װען מיר באַאָבאַכטען אַז אַ קערפּער פֿאַרענדערט זײן אָרט בנוגע צו אַ צװײטען
   קערפּער, זאָגען מיר, אַז ער באַװעגט זיך בנוגע צו דעם צװײטען
   קערפּער. באַװעגונג איז אַלזאָ - די פֿאַרענדערונג פֿון אָרט פֿון אַ קערפּער
   בנוגע צו אַ צװײטען קערפּער. דערבײ נעמען מיר געװײנליך נישט אין
   באַטראַכט, צי דער צװײטער קערפּער גופֿאַ געפֿינט זיך אין רו, אָדער צי
   באַװעגט ער זיך אױך בנוגע צו עפּעס אַ דריטען קערפּער. מיר זאָגען צ. ב.,
   אַז אַ צוג באַװעגט זיך רעלאַטיװ (בנוגע) צום באַן-װעג, נישט נעמענדיג
   דערבײ איןאַכט די באַװעגונג, װעלכע דער באַן-װעג פֿירט אױס צוזאַמען מיט
   דער גענצער ערד רעלאַטיװ צו דער זון.

   באַװעגונגען װערען צװישען זיך געמאַסטען לױט זײער שנעלקײט.

   פֿון טעגליכען לעבען װײסען מיר, אַז די שנעלקײט, מיט װעלכער אַ מענש מאַכט
   דורך אַ געװיסע שטרעקע, איז אָפּהענגיג, ערשטענס, פֿון דער לענג פֿון דער
   שטרעקע, און צװײטענס, פֿון דער צײט, װעלכע דער מענש באַדאַרף, כּדי די
   שטרעקע דורכצומאַכען. צ.ב. װען אַ שטרעקע פֿון 100 קילאָמעטער װערט
   דורכגעמאַכט אין 20 שעה, זאָגט מען, אַז די שנעלקײט פֿון גאַנג איז 5
   קילאָמעטער אין אַ שעה. מיט אַנדערע װערטער, די שנעלקײט איז אַ רעזולטאַט,
   װעלכען מען באַקומט, צוטײלענדיג די צאַל שטרעקע-אײנהײטען (100
   קילאָמעטער) אױף די צאַל צײט-אײנהײטען, אין װעלכע די שטרעקע װערט
   דורכגעמאַכט (20 שעה).

   מיר רעדען דערבײ נאָטירליך װעגען אַ שנעלקײט בנוגע צו אַ באַשטימטען
   קערפּער (אין אונזער בײשפּיל בנוגע צו דער ערד), װעלכען מיר באַטראַכטען
   פֿאַר רוהענדיג.

   לאָמיר זיך יעצט פֿאָרשטעלען, אַז אַ לאַנגער אײזענבאַן-צוג באַװעגט זיך מיט אַ
   געװיסער שנעלקײט (בנוגע צום באַנ-װעג), צ.ב. מיט אַ שנעלקײט פֿון 500
   מעטער אין אַ מינוט. אין צוג געפֿינט זיך אַ רײזענדער, װעלכער זיצט נישט
   אױף אײן אָרט, נור גײט אין דער לענג פֿון צוג. אין דער ריכטונג פֿון זײן
   באַװעגונג, מיט דער שנעלקײט פֿון 80 מעטער אין אַ מינוט. עס פֿרעגט זיך,
   מיט װאָס פֿאַר אַ שנעלקײט באַװעגט זיך דער רײזענדער רעלאַטיװ צום באַן-װעג?

   כּדי דאָס צו באַרעכענען, זאָגען מיר אַזױ: װען דער רײזענדער װאָלט געשטאַנען
   אין צוג אױף אײן אָרט, װאָלט ער געהאַט אין באַצוג צום באַן-װעג דיזעלביגע
   שנעלקײט, װאָס דער צוג גופֿאַ, ד.ה. די שנעלקײט פֿון 500 מעטער אין אַ
   מינוט. די דאָזיגע מינוט נוצט ער אַבער אױס, כּדי אין דוג גופֿאַ דורכצוגײן
   80 מעטער. מיר קומען דעריבער צום אױספֿיר, אַז דער רײזענדער מאַכט דורך
   אין באַצוג צום באַן-װעג יעדע מינוט 580 מעטער (500-80), ד.ה. ער האַט
   אין באַצוג צום באַן-װעג אַ שנעלקײט פֿון 580 מעטער אין אַ מינוט.
