#+latex_header: \usepackage[utf8]{inputenc}
* פֿאָרװאָרט
  מיטן פֿאָרליגענדען ביכּעל האָב איך מיר געשטעלט די אײַײַױפֿגאַבע באַקאַנט צו
  מאַכּען א ברײטערען עולם מיט די גרונד-יסודות פֿון אײנשטײנס
  רעלאטיװיטעטס-טעאָריע. איך האָב געהאַט אין זינען הױפּטזעכליך אַ לעזער, װאָס
  באַזיצט אױפֿן געביט פֿון מאַטעמאַטיק און נאַטורװיסענשאַפֿט נור גאַנץ װײניג
  קענטענישען, און האָב דעריבער נישט אַרײנגעפֿירט קײן מאַטעמאַטישע פֿאָרמולן,
  װעלכע װאָלטען אַזאַ לעזער נאָר אָפּגעשראַקען. צוליב דעמזעלביגען מעס האָב איך
  יעדען װיסענשאַפֿטליכען באַגריפֿ, װעלכען איך פֿיר אַרײן, צוערשט דעפֿינירט
  און גענױ ערקלערט, אַזױ אַז דאָס ביכעל קען מיתט ערפֿאָלג אױך אַ מענש,
  װעלכען די דערמאַנטע װיסענשאַפֿטען זענען לגמרי פֿרעמד.

  די באַאַרבײטונג פֿון פּראָבלעם אין דער ײדישער שפּראַך װעלכע איז נאָך צום
  באַדױערן אַזױ אַרעם אין װיסענשאַפֿטליכער ליטעראַטור און װעלכער עס פֿעלען
  נאָך מחמת דעם די נױטיגסטע װיסענשאַפֿטליכע אױסדרוקען, האַט געפֿאַדערט א סך
  מי. דאָס איז מיר באַדײטענד דערלײכטערט געװאַרען דורך דער הילף און
  מיטאַרבײט פֿון מײן פֿרײנד בנימין ראָזען, װעלכען איך דריק דאָ אױס דערפֿאַר א
  האַרציגען דאַנק. 

  פּראָפֿ. אַלבערט אײנשטײן האַט גענומען אױף זיך די מי זיך צו באַקענען מיטן
  אינהאַלט פֿון םײן אַרבײט און דערבײ םיר צו געבען מאַנכע װערטפֿולע
  עצות. פֿאַר זײן פֿרײנדליכע אױפֿמערקזאַמקײט דריק איך אים אױך דאַ אױס מײן
  טיפֿסטען דאַנק.

  אױב דאָס ביכעל װעט מיטהעלפֿען דעם לעזער צו באַגרײפֿען די טיפֿע און שײנע
  געדאַנקען פֿון דער רעלאַטיװיטעטס-טעאָריע און דערװעקען אין אים אַ אינטערעס
  װײטער און גרינדליכער זיך צו באַשעפֿטיגען מיט די באַרירטע פּראָבלעמען, װעט
  עס האָבען דערגרײכט זײן עיקר-ציל.

  יהודה לעהמאַן

  בערלינ, פֿעברואַר 1921
